name: Terraform CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    environment: dev
    env:
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"
      ENVIRONMENT: "dev"
      ACCOUNT_TIER: "Standard"
      ACCOUNT_REPLICATION_TYPE: "LRS"      
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false
      
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Export ARM_* for Terraform (OIDC)
        run: |
          {
            echo "ARM_USE_OIDC=true"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          } >> "$GITHUB_ENV"
      
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="./backend.hcl" \
            -backend-config="key=oblig2/${{ env.ENVIRONMENT }}/${{ env.ENVIRONMENT }}.tfstate" \
            -input=false \
            -no-color
      
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="account_tier=${{ env.ACCOUNT_TIER }}" \
            -var="account_replication_type=${{ env.ACCOUNT_REPLICATION_TYPE }}" \
            -no-color
      
      - name: Terraform Output
        id: output
        run: |
          echo "### Terraform Outputs for DEV" >> $GITHUB_STEP_SUMMARY
          terraform output -no-color | tee -a $GITHUB_STEP_SUMMARY

  deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: test
    env:
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"
      ENVIRONMENT: "test"
      ACCOUNT_TIER: "Premium"
      ACCOUNT_REPLICATION_TYPE: "GRS" 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false
      
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Export ARM_* for Terraform (OIDC)
        run: |
          {
            echo "ARM_USE_OIDC=true"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          } >> "$GITHUB_ENV"
      
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="./backend.hcl" \
            -backend-config="key=oblig2/${{ env.ENVIRONMENT }}/${{ env.ENVIRONMENT }}.tfstate" \
            -input=false \
            -no-color
      
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="account_tier=${{ env.ACCOUNT_TIER }}" \
            -var="account_replication_type=${{ env.ACCOUNT_REPLICATION_TYPE }}" \
            -no-color
      
      - name: Terraform Output
        id: output
        run: |
          echo "### Terraform Outputs for TEST" >> $GITHUB_STEP_SUMMARY
          terraform output -no-color | tee -a $GITHUB_STEP_SUMMARY

  deploy-prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    needs: deploy-test
    environment: prod
    env:
      TF_INPUT: "false"
      TF_IN_AUTOMATION: "true"
      ENVIRONMENT: "prod"
      ACCOUNT_TIER: "Premium"
      ACCOUNT_REPLICATION_TYPE: "GRS"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: false
      
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Export ARM_* for Terraform (OIDC)
        run: |
          {
            echo "ARM_USE_OIDC=true"
            echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"
            echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"
            echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          } >> "$GITHUB_ENV"
      
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="./backend.hcl" \
            -backend-config="key=oblig2/${{ env.ENVIRONMENT }}/${{ env.ENVIRONMENT }}.tfstate" \
            -input=false \
            -no-color
      
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="account_tier=${{ env.ACCOUNT_TIER }}" \
            -var="account_replication_type=${{ env.ACCOUNT_REPLICATION_TYPE }}" \
            -no-color
      
      - name: Terraform Output
        id: output
        run: |
          echo "### Terraform Outputs for PROD" >> $GITHUB_STEP_SUMMARY
          terraform output -no-color | tee -a $GITHUB_STEP_SUMMARY
      
      - name: Deployment Summary
        run: |
          echo "## 🎉 Deployment Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All environments have been successfully deployed:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ DEV" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ TEST" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ PROD" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Same Terraform code deployed to all environments!**" >> $GITHUB_STEP_SUMMARY